src/Models/CalcModel.cs
namespace app.Models {
    public class CalcModel
    {
        public int X { get; set; }
        public int Y { get; set; }
        public string Operation { get; set; }

        public string Calc()
        {
            return Operation switch
            {
                "+" => $"{X} + {Y} = {X + Y}",
                "-" => $"{X} - {Y} = {X - Y}",
                "*" => $"{X} * {Y} = {X * Y}",
                "/" when Y != 0 => $"{X} / {Y} = {X / Y}",
                "/" when Y == 0 => "zero division error",
                _ => "Invalid operation"
            };
        }
    }
}

src/Controllers/CalcServiceController.cs
using System;
using app.Models;
using Microsoft.AspNetCore.Mvc;


namespace app.Controllers {
    public class CalcServiceController : Controller {

        public IActionResult Index() {
            return View();
        }



        public IActionResult ManualParsingSingle() {
            if (Request.Method == System.Net.WebRequestMethods.Http.Post)
            {
                try
                {
                    var calc = new CalcModel
                    {
                        X = Int32.Parse(HttpContext.Request.Form["x"]),
                        Y = Int32.Parse(HttpContext.Request.Form["y"]),
                        Operation = HttpContext.Request.Form["operation"],
                    };

                    ViewBag.Result = calc.Calc();
                }
                catch
                {
                    ViewBag.Result = "Invalid input";
                }

                return View("Result");
            }
            return View("Form");
        }



        [HttpGet]
        [ActionName("ManualParsingSeparate")]
        public IActionResult ManualParsingSeparateGet()
        {
            return View("Form");
        }
        [HttpPost]
        [ActionName("ManualParsingSeparate")]
        public IActionResult ManualParsingSeparatePost() {
            try
            {
                var calc = new CalcModel
                {
                    X = Int32.Parse(HttpContext.Request.Form["x"]),
                    Y = Int32.Parse(HttpContext.Request.Form["y"]),
                    Operation = HttpContext.Request.Form["operation"],
                };

                ViewBag.Result = calc.Calc();
            }
            catch
            {
                ViewBag.Result = "Invalid input";
            }

            return View("Result");
        }



        [HttpGet]
        public IActionResult ModelBindingParameters()
        {
            return View("Form");
        }
        [HttpPost]
        public IActionResult ModelBindingParameters(int x, string operation, int y)
        {
            if (ModelState.IsValid)
            {
                var calc = new CalcModel
                {
                    X = x,
                    Y = y,
                    Operation = operation,
                };
                ViewBag.Result = calc.Calc();
            }
            else
            {
                ViewBag.Result = "Invalid input";
            }

            return View("Result");
        }



        [HttpGet]
        public IActionResult ModelBindingSeparate()
        {
            return View("Form");
        }
        [HttpPost]
        public IActionResult ModelBindingSeparate(CalcModel model)
        {
            ViewBag.Result = ModelState.IsValid
                ? model.Calc()
                : "Invalid input";

            return View("Result");
        }
    }
}

src/Views/CalcService/Form.cshtml
@{ var action = ViewContext.RouteData.Values["Action"] as string;
   var controller = ViewContext.RouteData.Values["Controller"] as string;
    ViewBag.Title = action; }

<h1>@action</h1>

@using (Html.BeginForm(action, controller, FormMethod.Post))
{
    @Html.TextBox("x", "", new { type = "number" })
    <br />
    @Html.DropDownList("operation", new SelectList(new[] { "+", "-", "*", "/" }))
    <br />
    @Html.TextBox("y", "", new {type="number" })
    <br />
<input type="submit" value="Submit" />


}

src/Views/CalcService/Index.cshtml
@{
    ViewBag.Title = "Home Page - Backend1";
}
<h1>Form parameters parsing demo</h1>
<ul>
    <li><a asp-controller="CalcService" asp-action="ManualParsingSingle">Manual parsing in single action</a></li>
    <li><a asp-controller="CalcService" asp-action="ManualParsingSeparate">Manual parsing in separate action</a></li>
    <li><a asp-controller="CalcService" asp-action="ModelBindingParameters">Model binding (parameters)</a></li>
    <li><a asp-controller="CalcService" asp-action="ModelBindingSeparate">Model binding (separate model)</a></li>
</ul>

src/Views/CalcService/Result.cshtml
@{ 
 ViewBag.Title = "Result";
}
<h1>Result</h1>
@ViewBag.Result

src/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <link rel="stylesheet" href="~/css/main.css" asp-append-version="true"/>
    <title>@ViewBag.Title</title>
</head>
<body>
<header>
    <h2>Backend1</h2>
    <nav><a asp-controller="CalcService" asp-action="Index">Home</a></nav>
</header>
<main>
    @RenderBody()
</main>
<footer>
    <hr/>
    © 2021 - backend
</footer>
</body>
</html>